name: ca
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dots_indicator: ^3.0.0
  intl_phone_number_input: ^0.7.2
  image_picker: ^1.0.5
  table_calendar: ^3.0.9
  path_provider: ^2.0.13
  sqflite: ^2.0.0
  flutter_barcode_scanner: ^2.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.0.12
  uuid: ^4.2.2
  package_info: ^2.0.2
  image: ^4.1.3
  async: ^2.9.0
  collection: ^1.17.1
  http: ^1.2.0
  latlong2: ^0.9.0
  logger: 1.4.0
  meta: ^1.9.1
  polylabel: ^1.0.1
  proj4dart: ^2.1.0
  vector_math: ^2.1.2
  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  url_launcher: ^6.2.2
  clipboard: ^0.1.3
  back_button_interceptor: ^7.0.0
  flutter_phone_direct_caller: ^2.1.1
  open_mail_app: ^0.4.5
  syncfusion_flutter_charts: ^25.2.3+1
  web_socket_channel: ^2.4.0
  webview_flutter: ^4.5.0
  json_annotation: ^4.0.0
  file_picker: ^8.0.0+1
  dropdown_search: ^5.0.6
  google_nav_bar: ^5.0.6
  line_icons: ^2.0.0
  google_fonts: any
  flutter_staggered_animations: ^1.0.0
  simple_animations: ^5.0.2
  badges: ^3.1.2
  glassmorphism: any
  anim_search_bar: ^2.0.2
  carousel_slider: ^4.1.1
  fluttertoast: ^8.0.8
  dropdown_button2: any
  flutter_colorpicker: ^1.0.3
  passwordfield: ^0.2.0
  expandable: any
  shimmer: ^3.0.0
  shamsi_date: any
  flutter_localizations:
    sdk: flutter
  flutter_riverpod:
  dio:
  dartz: 0.10.1
  go_router: ^14.1.0
  pinput: ^4.0.0
  cached_network_image: ^3.3.1
  substring_highlight: ^1.0.33
  flutter_screenutil: 5.9.0
  syncfusion_flutter_sliders: ^25.2.3
  font_awesome_flutter: ^10.6.0
  flutter_rating_bar: 4.0.1
  percent_indicator: 4.2.3
  freezed_annotation: 2.4.1
  internet_connection_checker: ^1.0.0+1
  connectivity_plus: 5.0.0
  device_imei: ^0.0.4+2
  geolocator: ^11.0.0
  awesome_notifications_core: ^0.9.0 # <~ always ensure to use the latest version
  awesome_notifications: any
  firebase_core: ^2.31.0
  firebase_messaging: ^14.9.2
  core:
    path: modules/core
  mirai_dropdown_menu: ^0.0.8+2
  floor: ^1.4.2
  path: ^1.8.3
  permission_handler: ^10.2.0

flutter_launcher_icons:
  android: true
  remove_alpha_ios: true
  image_path_android: "assets/images/ca-logo.png"

dependency_overrides:
  web: ^0.5.1


flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/app-logo.png" # Path to your icon image
  image_path_android: "assets/images/app-logo.png" # Path to your icon image for Android
  image_path_ios: "assets/images/app-logo.png" # Path to your icon image for iOS


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  hive_generator: ^2.0.1
  build_runner: ^2.0.5
  json_serializable: ^6.7.1
  flutter_lints: ^2.0.0
  floor_generator: ^1.4.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: DM Sans
      fonts:
        - asset: assets/fonts/DMSans-VariableFont_opsz_wght.ttf
          weight: 200
