// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2ItNbMMAN4ALb1bcvzkBKTVYK02UDjos',
    appId: '1:154222043881:web:2282d03d7afd4905198678',
    messagingSenderId: '154222043881',
    projectId: 'ca-junction-lko-24',
    authDomain: 'ca-junction-lko-24.firebaseapp.com',
    storageBucket: 'ca-junction-lko-24.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyhm29eMpbKwcDIwBYdi1l4t8VY_UtEIU',
    appId: '1:154222043881:android:ff457f956a68a94a198678',
    messagingSenderId: '154222043881',
    projectId: 'ca-junction-lko-24',
    storageBucket: 'ca-junction-lko-24.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5NEZGXY0Ekl14Yl_APJSVI4-v1IK37c8',
    appId: '1:154222043881:ios:ded6bdcf49fc0073198678',
    messagingSenderId: '154222043881',
    projectId: 'ca-junction-lko-24',
    storageBucket: 'ca-junction-lko-24.appspot.com',
    iosBundleId: 'com.example.ca',
  );

}